version: '3.8'

services:
  frontend:
    build: ./frontend-service
    ports:
      - "5005:5005"
    environment:
      - NODE_ENV=development
      - PORT=5005
      - API_URL=http://api-gateway:5000
    depends_on:
      - api-gateway
    volumes:
      - ./frontend-service:/app
      - /app/node_modules
    networks:
      - barber-network

  api-gateway:
    build: ./api-gateway
    ports:
      - "5000:5000"
    environment:
      - AUTH_SERVICE_URL=http://auth-service:5001
      - APPOINTMENTS_SERVICE_URL=http://appointments-service:5002
      - BARBERS_SERVICE_URL=http://barbers-service:5003
      - PRODUCTS_SERVICE_URL=http://products-service:5004
      - JWT_SECRET_KEY=your-super-secret-key-change-in-production
    depends_on:
      - auth-service
      - appointments-service
      - barbers-service
      - products-service
    networks:
      - barber-network

  auth-service:
    build: ./auth-service
    ports:
      - "5001:5001"
    environment:
      - DB_HOST=mysql-auth
      - DB_USER=root
      - DB_PASSWORD=secret
      - DB_NAME=auth_db
      - JWT_SECRET_KEY=your-super-secret-key-change-in-production
    depends_on:
      - mysql-auth
    networks:
      - barber-network
    volumes:
      - ./auth-service:/app
      - /app/__pycache__

  appointments-service:
    build: ./appointments-service
    ports:
      - "5002:5002"
    environment:
      - DB_HOST=mysql-appointments
      - DB_USER=root
      - DB_PASSWORD=secret
      - DB_NAME=appointments_db
    depends_on:
      - mysql-appointments
    networks:
      - barber-network
    volumes:
      - ./appointments-service:/app
      - /app/__pycache__

  barbers-service:
    build: ./barbers-service
    ports:
      - "5003:5003"
    environment:
      - DB_HOST=mysql-barbers
      - DB_USER=root
      - DB_PASSWORD=secret
      - DB_NAME=barbers_db
    depends_on:
      - mysql-barbers
    networks:
      - barber-network
    volumes:
      - ./barbers-service:/app
      - /app/__pycache__

  products-service:
    build: ./products-service
    ports:
      - "5004:5004"
    environment:
      - DB_HOST=mysql-products
      - DB_USER=root
      - DB_PASSWORD=secret
      - DB_NAME=products_db
    depends_on:
      - mysql-products
    networks:
      - barber-network
    volumes:
      - ./products-service:/app
      - /app/__pycache__

  mysql-auth:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=auth_db
    volumes:
      - mysql_auth_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - barber-network
    command: --default-authentication-plugin=mysql_native_password

  mysql-appointments:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=appointments_db
    volumes:
      - mysql_appointments_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - barber-network
    command: --default-authentication-plugin=mysql_native_password

  mysql-barbers:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=barbers_db
    volumes:
      - mysql_barbers_data:/var/lib/mysql
    ports:
      - "3308:3306"
    networks:
      - barber-network
    command: --default-authentication-plugin=mysql_native_password

  mysql-products:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=products_db
    volumes:
      - mysql_products_data:/var/lib/mysql
    ports:
      - "3309:3306"
    networks:
      - barber-network
    command: --default-authentication-plugin=mysql_native_password

networks:
  barber-network:
    driver: bridge

volumes:
  mysql_auth_data:
  mysql_appointments_data:
  mysql_barbers_data:
  mysql_products_data:
