apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: barber
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: api-gateway
        image: api-gateway:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        env:
        - name: AUTH_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: barber-config
              key: AUTH_SERVICE_URL
        - name: APPOINTMENTS_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: barber-config
              key: APPOINTMENTS_SERVICE_URL
        - name: BARBERS_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: barber-config
              key: BARBERS_SERVICE_URL
        - name: PRODUCTS_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: barber-config
              key: PRODUCTS_SERVICE_URL
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: barber-secrets
              key: jwt-secret-key
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: barber
spec:
  selector:
    app: api-gateway
  ports:
    - port: 5000
      targetPort: 5000
  type: ClusterIP 