apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-products-pvc
  namespace: barber
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-products
  namespace: barber
spec:
  selector:
    matchLabels:
      app: mysql-products
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql-products
    spec:
      containers:
      - name: mysql-products
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: barber-secrets
              key: mysql-root-password
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: barber-config
              key: DB_NAME_PRODUCTS
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-products-storage
          mountPath: /var/lib/mysql
        args: ["--default-authentication-plugin=mysql_native_password"]
      volumes:
      - name: mysql-products-storage
        persistentVolumeClaim:
          claimName: mysql-products-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-products
  namespace: barber
spec:
  selector:
    app: mysql-products
  ports:
    - port: 3306
      targetPort: 3306 